import { Metadata } from "next";
import Link from "next/link"; 
import React from "react";  
import Navbar from "../components/navbar/navbar";

export const metadata: Metadata = {
  title: {
    absolute: "Products", 
  },
  description: "Generated by create next app",
}; 

export default function Products() {
  
  return <>
    <h1>Products</h1>
    <Navbar />
    <ul> 
      <li><Link href="products/1">Product 1</Link></li>
      <li><Link href="products/2">Product 2</Link></li>
      <li><Link href="products/3" replace>Product 3</Link></li>
    </ul>
  </>;
}
